### ISSUE TITLE
Error when intalling Payget

### ISSUE THREAD

**Issue by josem1975** [Paygate/PayWeb_PrestaShop_1.6#2]
Hi There

Good Day!

We are getting below error when we install Paygate in Prestashop 1.6.1.6.
2 errors

    vcs (parse error in /modules/vcs/vcs.php)
    vcs (class missing in /modules/vcs/vcs.php)

Can you pls assit

**Comment by bruce-atkinson** [comment]
Kindly submit a support request to support@paygate.co.za with the relevant access details.
We will then do our best to assist and will amend this repo is so required.
